function(find_ign_lib)
    message(STATUS "Looking for ${ARGV0}")
    # get_cmake_property(_variableNames VARIABLES)
    # list (SORT _variableNames)
    set(ign_current ${ARGV1})
    set(ign_min_version ${ARGV2})
    while( ${ign_current} GREATER ${ign_min_version} )
        find_package(${ARGV0}${ign_current} QUIET)
        if(${ARGV0}${ign_current}_FOUND)
            message(STATUS "Found: ${ARGV0}${ign_current}")
            list(APPEND PRX_GZ_INCLUDE_DIRS ${ARGV0}${ign_current}_INCLUDE_DIRS)
            list(APPEND PRX_GZ_LIBRARY_DIRS ${ARGV0}${ign_current}_LIBRARY_DIRS)
            list(APPEND PRX_GZ_LIBRARIES ${ARGV0}${ign_current}_LIBRARIES)
            break()
        endif()
    endwhile()
endfunction()