data_path: "/common/users/dm1487/ktamp/random_goals"
# eval_data_path: ["/common/users/dm1487/ktamp/random/1"]
test_data_path: "/common/users/dm1487/ktamp/random_goals_test"

scene_goals: 289
balance_data: false