node_features: 13
edge_features: 2
node_hidden_dims: [64, 128, 256]
edge_hidden_dims: [32, 64]
gcn_hidden_dims: [256, 512, 512]
decoder_dims: [
        [512, 2, 2],
        [256, 4, 4],
        [128, 9, 9],
        [64, 17, 17]]
graph_predictor_hidden_dims: [64, 32]
output_size: 17
batch_size: 32
epochs: 50
device: cuda:0
learning_rate: 0.001
patience: 10
min_delta: 1e-4
scheduler_step_size: 10
scheduler_gamma: 0.5
classification_threshold: 0.5 # TODO: This should not be here
save_dir: saved_models
model_name: direct_objects_gnn_spatial_classifier