node_features: 14
edge_features: 2
node_hidden_dims: [128, 64, 32]
edge_hidden_dims: [32, 16]
gcn_hidden_dims: [128, 64, 32]
graph_predictor_hidden_dims: [32, 16]
output_dims: 1
batch_size: 512
epochs: 50
device: cuda:0
learning_rate: 0.001
patience: 10
min_delta: 1e-4
scheduler_step_size: 10
scheduler_gamma: 0.5
classification_threshold: 0.5 # TODO: This should not be here
save_dir: saved_models
model_name: direct_objects_gnn_classifier_gcn