# Input dimensions
mask_size: 40  # Size of input masks
latent_dim: 256  # Size of mask embeddings

# Decoder architecture
decoder_dims: [
    [512, 3, 3],
    [256, 5, 5],
    [128, 9, 9],
    [64, 17, 17]
]

# Training params
batch_size: 512
epochs: 50
device: cuda:0
learning_rate: 0.001
patience: 10
min_delta: 1e-4
scheduler_step_size: 10
scheduler_gamma: 0.5
save_dir: saved_models
model_name: mask_to_image_mlp_mixed  # Renamed from mask_to_image_gnn 
classification_threshold: 0.5