aggregate_data_path: /common/users/dm1487/ktamp_data_rename/cylinders_aggregate
controller_mode: push
data_path: /common/users/dm1487/ktamp_data_rename/cylinders/single_arc/env_config_2
discretization: 0.2
goal_radius: 0.1
goal_sampling_mode: discretized
goals_file: predictions/radius1/simple_scene_radius_gnn/goal_lists/env_config_4512.txt
nav:
  allow_collision: false
  control_scale: 0.3
num_random_goals: 300
push:
  allow_collision: true
  control_scale: 1.0
radius_step: 0.05
random_seed: 1
step_duration: 0.01
time_limit: 40
visualize: false
xml_path: cylinders/single_arc/env_config_2.xml
