random_seed: 1
xml_path: push/model_object_interactions_6_bottlenecks.xml
planner_name: "dirt"

checker_type: time
checker_value: 10
output_plan: true
goal_position: [3.2, 0.0, 0.05]
output_tree_folder: "/home/dhruv/2024/projects/NAMO/out/trees/"
output_plan_file: "/home/dhruv/2024/projects/NAMO/out/1_5.txt"
output_folder: "/home/dhruv/2024/projects/NAMO/out/object_interactions_6_bottlenecks/29Jul/subgoals_room2room_blossomics_t120/"
subgoals_file: "/home/dhruv/2024/projects/ml4kp_ktamp/build/object_interactions_6_bottlenecks/subgoals_room2room.txt"
visualize: false
do_subgoals: true
num_trials: 30

navigate:
  env_xlim: [-0.13, 3.4]
  env_ylim: [-0.2, 0.2]
  min_control_steps: 0.1
  max_control_steps: 1.0
  ignored_pairs: []
  goal_pos_region_radius: 0.05
  goal_vel_region_radius: 0.01
  max_vel: 20
  blossom: 10
  use_pruning: false
  visualize_tree: true
  ics:
    do_ics_check: true
    type: "blossom" # ["bang-bang", "blossom"] if bang-bang set duration (defaults to 0.5), if blossom set blossom (defaults to 25)
    duration: 0.5
    blossom: 25

  condition_checker:
    type: "time"
    value: 120
    first_solution: true

manipulate:
  env_xlim: [-0.1, 1.5]
  env_ylim: [-0.25, 0.25]
  min_control_steps: 0.1
  max_control_steps: 1.0
  ignored_pairs: []
  goal_pos_region_radius: 0.1
  goal_angle_region_radius: 0.1
  goal_vel_region_radius: 0.0001
  max_vel: 20
  blossom: 1
  use_pruning: false
  visualize_tree: true