random_seed: 1
xml_path: push/turning_interactions/12.xml
planner_name: "dirt"

checker_type: time
checker_value: 10
output_plan: true
goal_position: [6.4, 0.0, 0.05]
output_tree_folder: "/home/dhruv/2024/projects/NAMO/out/trees/"
output_plan_file: "/home/dhruv/2024/projects/NAMO/out/1_5.txt"
output_folder: "/home/dhruv/2024/projects/NAMO/out/turning_interactions/12/4Aug/no_subgoals_1/"
subgoals_file: "/home/dhruv/2024/projects/ml4kp_ktamp/build/turning_interactions/12/subgoals_room2room.txt"
visualize: false
do_subgoals: false
num_trials: 30

navigate:
  env_xlim: [-0.13, 6.6]
  env_ylim: [-0.19, 0.19]
  min_control_steps: 0.1
  max_control_steps: 1.0
  ignored_pairs: []
  goal_pos_region_radius: 0.05
  goal_vel_region_radius: 0.01
  max_vel: 20
  blossom: 10
  use_pruning: false
  visualize_tree: true
  condition_checker:
    type: "time"
    value: 600
    first_solution: true 
  ics:
    do_ics_check: true
    type: "bang-bang" # ["bang-bang", "blossom"] if bang-bang set duration (defaults to 0.5), if blossom set blossom (defaults to 25)
    duration: 1
    blossom: 25

manipulate:
  env_xlim: [-0.1, 1.5]
  env_ylim: [-0.25, 0.25]
  min_control_steps: 0.1
  max_control_steps: 1.0
  ignored_pairs: []
  goal_pos_region_radius: 0.1
  goal_angle_region_radius: 0.1
  goal_vel_region_radius: 0.0001
  max_vel: 20
  blossom: 1
  use_pruning: false
  visualize_tree: true