random_seed: 15
xml_path: push/turning_interactions/6.xml
planner_name: "dirt"

checker_type: time
checker_value: 10
output_plan: true
goal_position: [3.4, 0.0, 0.05]
output_tree_folder: "/home/dhruv/2024/projects/NAMO/out/trees/"
output_plan_file: "/home/dhruv/2024/projects/NAMO/out/1_5.txt"
output_folder: "/home/dhruv/2024/projects/NAMO/out/turning_interactions/6/22Aug/subgoals_room2room_nobnb_walls_final3/"
subgoals_file: "/home/dhruv/2024/projects/ml4kp_ktamp/build/turning_interactions/6/subgoals_room2room.txt"
visualize: false
do_subgoals: true
backtrack: true
num_trials: 10

# collision_pairs: [
#   ["ball", "case"],
#   ["ball", "wall_1"], ["ball", "wall_2"], ["ball", "wall_3"], ["ball", "wall_4"], ["ball", "wall_5"], ["ball", "wall_6"]] 
#   ["ball", "wall_7"], ["ball", "wall_8"], ["ball", "wall_9"], ["ball", "wall_10"], ["ball", "wall_11"], ["ball", "wall_12" , ]] 
#   ["ball", "wall_13"], ["ball", "wall_14"], ["ball", "wall_15"], ["ball", "wall_16"], ["ball", "wall_17"], ["ball", "wall_18"], ["ball", "wall_19"], ["ball", "wall_20"], ["ball", "wall_21"], ["ball", "wall_22"], ["ball", "wall_23"], ["ball", "wall_24"]
# ]

navigate:
  env_xlim: [-0.13, 3.6]
  env_ylim: [-0.2, 0.2]
  min_control_steps: 0.1
  max_control_steps: 1.0
  ignored_pairs: []
  goal_pos_region_radius: 0.05
  goal_vel_region_radius: 0.01
  max_vel: 20
  blossom: 10
  bnb: false
  use_pruning: false
  visualize_tree: true
  condition_checker:
    type: "time"  
    value: 20
    first_solution: true 
  ics:
    do_ics_check: false
    type: "bang-bang" # ["bang-bang", "blossom"] if bang-bang set duration (defaults to 0.5), if blossom set blossom (defaults to 25)
    duration: 1
    blossom: 25

manipulate:
  env_xlim: [-0.1, 1.5]
  env_ylim: [-0.25, 0.25]
  min_control_steps: 0.1
  max_control_steps: 1.0
  ignored_pairs: []
  goal_pos_region_radius: 0.1
  goal_angle_region_radius: 0.1
  goal_vel_region_radius: 0.0001
  max_vel: 20
  blossom: 1
  use_pruning: false
  visualize_tree: true